spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Blogs
    username: sa
    password: Passw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #  dialect: org.hibernate.dialect.SQLServer2012Dialect
    #  ddl-auto: create-drop
